/**
 * Per-block re-narration (AB#7412 — plan §3, "Editing and re-narration").
 *
 * > "Re-narrating a whole book because one typo changed is unacceptable. The
 * >  pipeline already content-hashes chapters; extend that per block, so an
 * >  edit re-generates only the blocks that actually changed and splices the
 * >  audio. That makes 'fix a typo' cheap enough to actually use."
 *
 * ── Why this is a thin layer and not a new pipeline ─────────────────────────
 * The TTS providers already work a block at a time: `synthesizeChapter()` in
 * both `tts.mjs` (Azure) and `tts-kokoro.mjs` (local Kokoro) emits one MP3
 * chunk plus one word-timing array PER BLOCK, and `stitch.mjs` concatenates
 * those chunks and shifts each block's word timings by the measured (ffprobe)
 * offset of its chunk. Everything needed for partial re-narration was already
 * there except a memory of what had been narrated before.
 *
 * So this file adds exactly that memory — a content-addressed cache of block
 * chunks — and nothing else:
 *
 *     <cacheDir>/<blockAudioKey>.mp3          the block's narration
 *     <cacheDir>/<blockAudioKey>.words.json   its word timings, block-relative
 *
 * ── The key is the same hash that keeps block ids stable ────────────────────
 * `blockAudioKey()` hashes `{ type, plain text }` — deliberately the SAME
 * function `stabilizeBlockIds()` uses in md.mjs. That equality is the whole
 * design:
 *
 *   • A block whose text is untouched keeps its id AND its audio, even if
 *     every other block in the chapter moved.
 *   • A block whose text changed gets a new key, so it is re-synthesized even
 *     when `stabilizeBlockIds` handed its old id back to it.
 *   • Two blocks with identical text share one chunk — synthesized once,
 *     spliced in twice.
 *
 * Keying on text rather than on block id is what makes an insertion cheap:
 * adding a paragraph at the top of a chapter renumbers every block after it,
 * and an id-keyed cache would re-narrate the entire chapter for it.
 *
 * ── Splicing ────────────────────────────────────────────────────────────────
 * There is no bespoke splice. The final chunk list is rebuilt in the chapter's
 * CURRENT block order, mixing cache hits and fresh chunks, and handed to the
 * existing `stitchChapter()`. That matters for correctness of the word-sync
 * highlighting: stitch re-probes every chunk's real duration and re-derives
 * every block's `startMs` and word offsets from scratch, so a reused chunk that
 * now sits 40 seconds later in the chapter gets timings for where it actually
 * is. Word timings are stored block-relative precisely so they survive being
 * moved.
 *
 * ── Degradation ─────────────────────────────────────────────────────────────
 * An empty or missing cache means every block is a miss, which is byte-for-byte
 * the behaviour that existed before this file. Deleting `.storylark/work/` is
 * therefore always safe; it costs a full re-narration, never a wrong one.
 */

import { copyFile, mkdir, readFile, readdir, rm, stat, unlink, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { blockPlainText, contentHash } from './md.mjs';

/** A scene break is a beat of silence, not narration — generated by stitch. */
export const SILENCE_MS = 900;

/**
 * How many chunks for blocks that are no longer in the chapter to keep around.
 *
 * Not zero, and that is a decision rather than an oversight. Plan §3 keeps five
 * TEXT revisions per chapter and offers a revert button, so "edit, look at it,
 * put it back" is a normal afternoon — and if the previous chunk were deleted
 * the moment the edit landed, every revert would pay for a re-narration of text
 * that was already narrated an hour ago.
 *
 * So orphans linger, oldest-first, up to a budget scaled to the chapter. The
 * cost is bounded (a few hundred KB per chapter of MP3 in a build directory
 * that is already gitignored) and the benefit is that undoing is as cheap as
 * doing.
 */
export const ORPHAN_BUDGET = 40;

/**
 * The cache key for one block's narration: a hash of what will be SPOKEN.
 *
 * Identical to the hash `stabilizeBlockIds()` matches on, on purpose — see the
 * file header. Note what is excluded: the block's id, its position, its spans
 * and (for images) its src. None of those change a single sample of audio, so
 * none of them should cost a re-narration.
 */
export function blockAudioKey(block) {
  return contentHash({ t: block.type, x: blockPlainText(block) });
}

/**
 * Decide, without synthesizing anything, what a chapter's narration would cost.
 *
 * Split out from the synthesis path so `publish --dry-run` can report the real
 * number of blocks a re-narration would touch instead of "this chapter
 * changed" — which is the difference between an operator knowing an edit costs
 * one paragraph and assuming it costs the book.
 */
export function planChapterAudio(blocks, cacheDir, { force = false } = {}) {
  const items = [];
  const wanted = new Set();
  let reused = 0;
  let resynthesized = 0;
  let charCount = 0;

  for (const block of blocks) {
    const text = blockPlainText(block);
    if (!text.trim()) {
      // Unspeakable blocks: scene breaks become silence, images and anything
      // else contribute nothing at all.
      if (block.type === 'scene-break') items.push({ kind: 'silence', blockId: block.id, silenceMs: SILENCE_MS });
      continue;
    }
    const key = blockAudioKey(block);
    wanted.add(key);
    const audioFile = join(cacheDir, `${key}.mp3`);
    const wordsFile = join(cacheDir, `${key}.words.json`);
    const hit = !force && existsSync(audioFile) && existsSync(wordsFile);
    if (hit) reused++;
    else {
      resynthesized++;
      charCount += text.length;
    }
    items.push({ kind: hit ? 'cached' : 'synthesize', blockId: block.id, block, key, audioFile, wordsFile, chars: text.length });
  }

  return {
    items,
    wanted,
    reused,
    resynthesized,
    /** Characters that would actually be sent to a paid provider this run. */
    charCount,
    speakable: reused + resynthesized,
  };
}

/** One line an operator can act on: what this chapter's narration will cost. */
export function describeChapterAudio(plan) {
  if (plan.speakable === 0) return 'no narratable blocks';
  if (plan.resynthesized === 0) return `0 of ${plan.speakable} blocks need narration (all reused)`;
  if (plan.reused === 0) return `${plan.resynthesized} of ${plan.speakable} blocks need narration (nothing cached)`;
  return `${plan.resynthesized} of ${plan.speakable} blocks need narration, ${plan.reused} reused (${plan.charCount} chars)`;
}

/**
 * Narrate a chapter, re-synthesizing only the blocks whose text actually
 * changed, and return the same `{ chunks, blockTimings, charCount }` shape
 * `synthesizeChapter()` returns — so `stitchChapter()` consumes it unchanged.
 *
 * `options.synthesize` is the single injection point for the real TTS call. It
 * is given a chapter-shaped object holding ONLY the blocks that need audio and
 * must honour the provider contract (one `chunk-<blockId>.mp3` per speakable
 * block in `dir`, plus block-relative word timings). Left unset, the provider
 * is chosen from the voice id exactly as publish.mjs has always chosen it.
 */
export async function synthesizeChapterIncremental(chapter, voice, workDir, options = {}) {
  const {
    cacheDir = join(workDir, 'blocks'),
    synthesize,
    force = false,
    prune = true,
    orphanBudget = ORPHAN_BUDGET,
    onProgress,
    ...providerOptions
  } = options;

  await mkdir(cacheDir, { recursive: true });
  const plan = planChapterAudio(chapter.blocks, cacheDir, { force });

  // Dedupe by key: a chapter that repeats a line verbatim pays for it once.
  const pending = [];
  const byKey = new Map();
  for (const item of plan.items) {
    if (item.kind !== 'synthesize' || byKey.has(item.key)) continue;
    byKey.set(item.key, item);
    pending.push(item);
  }

  let charCount = 0;
  if (pending.length > 0) {
    const synth = synthesize ?? (await defaultSynthesizer(voice));
    // Staged outside the cache proper so a synthesis that dies half way through
    // can never leave a truncated chunk behind under a key that would then be
    // treated as a hit forever.
    const stageDir = join(cacheDir, 'staging');
    await rm(stageDir, { recursive: true, force: true });
    await mkdir(stageDir, { recursive: true });

    // Blocks are handed over under their KEY as id, so the chunk filenames the
    // provider writes are already cache-addressed and two blocks that happen to
    // share an id (across a rename) cannot collide.
    const subChapter = { ...chapter, blocks: pending.map((p) => ({ ...p.block, id: p.key })) };
    const result = await synth(subChapter, voice, stageDir, {
      ...providerOptions,
      onProgress: onProgress ? (id, chars) => onProgress(byKey.get(id)?.blockId ?? id, chars) : undefined,
    });
    charCount = result.charCount ?? 0;

    const wordsByKey = new Map((result.blockTimings ?? []).map((t) => [t.blockId, t.words]));
    const produced = new Set();
    for (const chunk of result.chunks ?? []) {
      if (chunk.silenceMs || !chunk.file) continue;
      const item = byKey.get(chunk.blockId);
      if (!item) continue;
      // copy+unlink rather than rename: same result, no platform differences
      // over replacing an existing destination.
      await copyFile(chunk.file, item.audioFile);
      await unlink(chunk.file).catch(() => {});
      await writeFile(item.wordsFile, JSON.stringify(wordsByKey.get(chunk.blockId) ?? []));
      produced.add(item.key);
    }
    const missing = pending.filter((p) => !produced.has(p.key));
    if (missing.length > 0) {
      // Loud rather than silent: a block with text and no audio would publish
      // as a gap in the narration that nothing else in the pipeline notices.
      throw new Error(
        `TTS produced no audio for ${missing.length} block(s) that need it: ${missing.map((m) => m.blockId).join(', ')}`
      );
    }
    await rm(stageDir, { recursive: true, force: true });
  }

  // Rebuild the chunk list in the chapter's CURRENT order — the splice.
  const chunks = [];
  const blockTimings = [];
  for (const item of plan.items) {
    if (item.kind === 'silence') {
      chunks.push({ blockId: item.blockId, silenceMs: item.silenceMs });
      continue;
    }
    chunks.push({ blockId: item.blockId, file: item.audioFile });
    blockTimings.push({ blockId: item.blockId, words: JSON.parse(await readFile(item.wordsFile, 'utf8')) });
  }

  if (prune) await pruneCache(cacheDir, plan.wanted, orphanBudget);

  return {
    chunks,
    blockTimings,
    /** Only what was actually synthesized this run — this is what a metered
     *  provider bills for, and what publish.mjs adds to its character ledger. */
    charCount,
    reused: plan.reused,
    /** Blocks that needed new audio. */
    resynthesized: plan.resynthesized,
    /** Provider calls actually made — lower than `resynthesized` when a chapter
     *  repeats a line verbatim, since identical text is narrated once. */
    synthesized: pending.length,
    speakable: plan.speakable,
  };
}

/**
 * Bound the cache: keep every chunk the chapter currently uses, plus the most
 * recent orphans up to `budget`, and delete the oldest beyond that.
 *
 * Ordered by mtime, which for a chunk is when it was synthesized — so what
 * survives is what was narrated most recently, which is what a revert is most
 * likely to want back.
 */
async function pruneCache(cacheDir, wanted, budget) {
  let entries;
  try {
    entries = await readdir(cacheDir, { withFileTypes: true });
  } catch {
    return;
  }
  const orphans = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const m = /^([0-9a-f]+)\.mp3$/.exec(entry.name);
    if (!m || wanted.has(m[1])) continue;
    const s = await stat(join(cacheDir, entry.name)).catch(() => null);
    if (s) orphans.push({ key: m[1], mtimeMs: s.mtimeMs });
  }
  if (orphans.length <= budget) return;
  orphans.sort((a, b) => b.mtimeMs - a.mtimeMs);
  for (const { key } of orphans.slice(budget)) {
    await unlink(join(cacheDir, `${key}.mp3`)).catch(() => {});
    await unlink(join(cacheDir, `${key}.words.json`)).catch(() => {});
  }
}

async function defaultSynthesizer(voice) {
  const { isKokoroVoice } = await import('../tts-kokoro.mjs');
  const mod = isKokoroVoice(voice) ? await import('../tts-kokoro.mjs') : await import('../tts.mjs');
  return mod.synthesizeChapter;
}
